apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ingress-host-sync-cronjob
spec:
  schedule: "*/1 * * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: sync
            image: localhost:32000/microk8s-sync-hosts
            imagePullPolicy: Always
            args:
              - '--host-pattern=<CHANGE ME>'
            volumeMounts:
              - mountPath: /etc/hosts
                name: hostsfile
          volumes:
            - name: hostsfile
              hostPath:
                path: /etc/hosts
          restartPolicy: Never
